# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Pythoner
email: hxflove521@sina.com 
description:  少壮不努力老大徒伤悲
baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "http://www.happy-life.top" # the base hostname & protocol for your site
twitter_username: hexiaofeng
github_username:  hxflove521

# Build settings
markdown: kramdown
